version: '2'
services:
  spark-master:
    build:
      context: .
      dockerfile: spark-container/Dockerfile
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    command: /start-master
  spark-worker-1:
    build:
      context: .
      dockerfile: spark-container/Dockerfile
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    command: /start-worker